---
name: Continuous Integration

on:
  push:
    branches:
      - embedded
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2
  GTEST_COLOR: 1

jobs:
  host_build_test_ubuntu:
    name: Host Build & Test (ubuntu-latest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          persist-credentials: false
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}
      - uses: hendrikmuhs/ccache-action@ca3acd2731eef11f1572ccb126356c2f9298d35e # v1.2.9
        with:
          key: ${{ github.job }}-ubuntu-latest
          variant: sccache
      - uses: lukka/run-cmake@c2b72aff009141774c5a5fabe74ea46c8c04d9c4 # v10.6
        with:
          configurePreset: "continuous-integration"
          buildPreset: "continuous-integration"
          testPreset: "continuous-integration"
          configurePresetAdditionalArgs: "['-DCMAKE_C_COMPILER_LAUNCHER=sccache', '-DCMAKE_CXX_COMPILER_LAUNCHER=sccache']"
      - name: Upload test logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: test-logs
          path: build/continuous-integration/Testing/Temporary/
  host_build_test:
    name: Host Build & Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, windows-2019]
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          persist-credentials: false
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}
      - uses: hendrikmuhs/ccache-action@ca3acd2731eef11f1572ccb126356c2f9298d35e # v1.2.9
        with:
          key: ${{ github.job }}-${{ matrix.os }}
          variant: sccache
      - uses: lukka/run-cmake@c2b72aff009141774c5a5fabe74ea46c8c04d9c4 # v10.6
        with:
          configurePreset: "continuous-integration"
          buildPreset: "continuous-integration"
          testPreset: "continuous-integration"
          configurePresetAdditionalArgs: "['-DCMAKE_C_COMPILER_LAUNCHER=sccache', '-DCMAKE_CXX_COMPILER_LAUNCHER=sccache']"
      - name: Upload test logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: test-logs
          path: build/continuous-integration/Testing/Temporary/
  embedded_build:
    name: Embedded Build
    runs-on: ubuntu-latest
    needs: [host_build_test_ubuntu]
    strategy:
      matrix:
        gcc: ["7-2018-q2", "8-2019-q3", "9-2020-q2", "10.3-2021.10"]
        configuration: ["RelWithDebInfo"]
        hardware: ["EK-TM4C1294XL-Custom"]
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          persist-credentials: false
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}
      - name: Install GNU Arm Embedded Toolchain ${{ matrix.gcc }}
        uses: carlosperate/arm-none-eabi-gcc-action@87cd4a1b01dad71985108eff5e2f3577a815f6b4 # v1.6.2
        with:
          release: ${{ matrix.gcc }}
      - run: sudo apt-get update && sudo apt-get install ninja-build
      - uses: hendrikmuhs/ccache-action@ca3acd2731eef11f1572ccb126356c2f9298d35e # v1.2.9
        with:
          key: ${{ github.job }}-${{ matrix.gcc }}-${{ matrix.configuration }}
      - uses: lukka/run-cmake@c2b72aff009141774c5a5fabe74ea46c8c04d9c4 # v10.6
        with:
          configurePreset: "${{ matrix.hardware }}"
          buildPreset: "${{ matrix.hardware }}-${{ matrix.configuration }}"
          configurePresetAdditionalArgs: "['-DCMAKE_C_COMPILER_LAUNCHER=ccache', '-DCMAKE_CXX_COMPILER_LAUNCHER=ccache']"

  # rtos:
  #   name: Embedded Build - RTOS
  #   runs-on: ubuntu-latest
  #   needs: [host_build_test_ubuntu]
  #   strategy:
  #     matrix:
  #       rtos: ["FreeRTOS", "ThreadX"]
  #   steps:
  #     - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
  #       with:
  #         persist-credentials: false
  #         submodules: recursive
  #     - name: Install GNU Arm Embedded Toolchain "10.3-2021.10"
  #       uses: carlosperate/arm-none-eabi-gcc-action@87cd4a1b01dad71985108eff5e2f3577a815f6b4 # v1.6.2
  #       with:
  #         release: "10.3-2021.10"
  #     - run: sudo apt-get update && sudo apt-get install ninja-build
  #     - uses: hendrikmuhs/ccache-action@ca3acd2731eef11f1572ccb126356c2f9298d35e # v1.2.9
  #       with:
  #         key: ${{ github.job }}
  #     - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
  #       with:
  #         name: emil
  #     - run: tar -zxvf emil-*.tar.gz
  #     - run: mkdir install && mv emil-*/* install/
  #     - uses: lukka/run-cmake@c2b72aff009141774c5a5fabe74ea46c8c04d9c4 # v10.6
  #       with:
  #         configurePreset: "Embedded-${{ matrix.rtos }}"
  #         buildPreset: "Embedded-${{ matrix.rtos }}-RelWithDebInfo"
  #         configurePresetAdditionalArgs: "['-DCMAKE_C_COMPILER_LAUNCHER=ccache', '-DCMAKE_CXX_COMPILER_LAUNCHER=ccache']"
