---
  name: Create Release

  on:
    workflow_dispatch:
    push:
      branches: [embedded]

  permissions:
    contents: read

  concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

  jobs:
    release_please:
      permissions: write-all
      name: Create Release
      runs-on: ubuntu-latest
      outputs:
        releases_created: ${{ steps.release.outputs.releases_created }}
        tag_name: ${{ steps.release.outputs.tag_name }}
      steps:
        - uses: google-github-actions/release-please-action@4c5670f886fe259db4d11222f7dff41c1382304d # v3.7.12
          id: release
          with:
            command: manifest
            release-type: simple
            token: ${{ secrets.GITHUB_TOKEN }}
