---
name: Security

on:
  workflow_dispatch:
  branch_protection_rule:
  schedule:
    - cron: "33 8 * * 6"
  push:
    branches: [main]

permissions: read-all

jobs:
  analysis:
    name: OSSF Scorecards
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          persist-credentials: false
          submodules: recursive
      - name: Analysis
        uses: ossf/scorecard-action@08b4669551908b1024bb425080c797723083c031 # v2.2.0
        with:
          results_file: scorecards.sarif
          results_format: sarif
          repo_token: ${{ secrets.SCORECARD_READ_TOKEN }}
          publish_results: true
      - uses: github/codeql-action/upload-sarif@2cb752a87e96af96708ab57187ab6372ee1973ab # v2.22.0
        with:
          sarif_file: scorecards.sarif
